Feature/ot210 19
alkemyTech/OT210-server pull request #3
Opened 2022-05-20 23:18 UTC by vongolaARZ

se agrego la entidad new, su respectivo script y el repo.
AVISO: esta entidad posee una relacion con la entidad Category por lo cual deberian pullerse al mismo tiempo

2022-05-21 10:32 UTC, manerajona commented
@vongolaARZ podrías usar el template del proyecto por favor (te debería aparecer cuando creas el pr). https://github.com/alkemyTech/OT210-server/blob/main/.github/pull_request_template.md

2022-05-21 10:37 UTC, manerajona commented
@vongolaARZ cambiar el título de pr a `[OT210-19] Crear modelo y repositorio base de Categories` por favor

2022-05-21 10:37 UTC, manerajona commented
@vongolaARZ cambiar el título de pr a `[OT210-19] Crear modelo y repositorio base de Categories` por favor

2022-05-21 14:09 UTC, vongolaARZ commented
pero cree el modelo y el repositorio no aparece?

2022-05-28 12:04 UTC, manerajona requested changes

2022-05-28 12:04 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/New.java
> +@SQLDelete(sql = "UPDATE new SET i@EntityListeners(AuditListener.class)s_active=false WHERE new_id=?")
Revisar este update por favor

2022-05-28 12:04 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/New.java
> +
Falta Category

2022-05-28 12:04 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/New.java
> +
Falta Category

2022-05-28 12:04 UTC, manerajona commented on src/main/resources/db/migration/V1.19__create_table_new.sql
> +    primary key (new_id)
Falta la relación con category

2022-05-28 12:04 UTC, manerajona commented on src/main/resources/db/migration/V1.19__create_table_new.sql
> +    primary key (new_id)
Falta la relación con category

2022-05-29 13:47 UTC, merged