[OT210-44] Adding Delete Category
alkemyTech/OT210-server pull request #41
Opened 2022-06-04 13:39 UTC by RodrigoMdza

## Why is this change required?

### Motivation and Summary

COMO usuario administrador
QUIERO eliminar una categoría existente
PARA mantener la información actualizada

Criterios de aceptación:
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla.

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-06-04 14:13 UTC, manerajona commented
@RodrigoMdza tiene conflictos con main

2022-06-04 22:29 UTC, manerajona requested changes

2022-06-04 22:29 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/CategoryServiceImpl.java
> +    @Override
Por favor agregar al método la anotación `@Transactional`

2022-06-04 22:29 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
Por favor retornar 204 NO CONTENT

2022-06-05 13:43 UTC, manerajona requested changes

2022-06-05 13:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/CategoryServiceImpl.java
> +        categoryJpaRepository.deleteById(id);
Esta tirando error 500 si se pasa un id que no existe, seguir el ejemplo: https://github.com/alkemyTech/OT210-server/blob/main/src/main/java/com/alkemy/ong/domain/usecase/impl/AlkymerServiceImpl.java#L62

<img width="982" alt="image" src="https://user-images.githubusercontent.com/21185543/172053638-f05d900f-052d-4682-b7b7-f85aaec4bc2b.png">

2022-06-05 13:46 UTC, RodrigoMdza commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
Corregido

2022-06-05 13:56 UTC, RodrigoMdza commented on src/main/java/com/alkemy/ong/domain/usecase/impl/CategoryServiceImpl.java
> +        categoryJpaRepository.deleteById(id);
Corregido

2022-06-05 21:39 UTC, merged