adding slides entity, repository and script
alkemyTech/OT210-server pull request #5
Opened 2022-05-22 02:50 UTC by RodrigoMdza

## Why is this change required?

### Motivation and Summary

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-05-22 02:51 UTC, RodrigoMdza commented
Adding Slides Entity, Repository and Script.

2022-05-27 11:24 UTC, manerajona requested changes

2022-05-27 11:24 UTC, manerajona commented on src/main/resources/db/migration/V1.28__create_table_slides.sql
> +create table slides
Por favor sigamos la convención de nombres en **singular**.

2022-05-27 11:24 UTC, manerajona commented on src/main/resources/db/migration/V1.28__create_table_slides.sql
> +create table slides
Por favor sigamos la convención de nombres en **singular**.

2022-05-27 11:24 UTC, manerajona commented on src/main/resources/application.properties
> +spring.datasource.password=root
Por favor no subamos estos cambios en el application.properties.

2022-05-27 11:24 UTC, manerajona commented on src/main/resources/application.properties
> +spring.datasource.password=root
Por favor no subamos estos cambios en el application.properties.

2022-05-27 11:24 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slides.java
> +public class Slides implements Auditable {
Por favor sigamos la convención de nombres en **singular**.

2022-05-27 11:24 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slides.java
> +public class Slides implements Auditable {
Por favor sigamos la convención de nombres en **singular**.

2022-05-27 11:24 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slides.java
> +    @ManyToOne
Por favor agregarle `@OneToMany(fetch = FetchType.LAZY)`

2022-05-27 11:24 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slides.java
> +    @ManyToOne
Por favor agregarle los siguentes flags: `@OneToMany(fetch = FetchType.LAZY)`

2022-05-27 15:02 UTC, RodrigoMdza commented on src/main/resources/db/migration/V1.28__create_table_slides.sql
> +create table slides
Corregido.

2022-05-28 12:10 UTC, manerajona requested changes

2022-05-28 12:10 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +import com.amazonaws.services.guardduty.model.Organization;
Eliminar esta dependencia por favor, está dando error de compilación

2022-05-28 12:10 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +@Table(name = "slides")
Cambiar a singular

2022-05-28 12:10 UTC, manerajona commented on src/main/resources/application.properties
> -#spring.datasource.password=password
No subir cambios al `application.properties`

2022-05-28 12:10 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +    private Organization organizationId;
Cambiar el nombre del atributo a `organization` por favor

2022-05-28 21:30 UTC, RodrigoMdza commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +import com.amazonaws.services.guardduty.model.Organization;
Corregido.

2022-05-28 21:30 UTC, RodrigoMdza commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +@Table(name = "slides")
Corregido.

2022-05-28 21:30 UTC, RodrigoMdza commented on src/main/resources/application.properties
> -#spring.datasource.password=password
Corregido.

2022-05-28 21:30 UTC, RodrigoMdza commented on src/main/java/com/alkemy/ong/domain/model/Slide.java
> +    private Organization organizationId;
Corregido.

2022-05-29 14:00 UTC, merged