[OT210-71] Endpoint Members Update created
alkemyTech/OT210-server pull request #62
Opened 2022-06-09 21:39 UTC by hernancostarelli

## Why is this change required?

### Motivation and Summary

Descripción

COMO usuario
QUIERO actualizar los Miembros
PARA mantener la información actualizada.

Criterios de aceptación:
PUT /members/:id - Deberá validar que el miembro existe y actualizarla, caso contrario devolver un error

### Type of change
- [x] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [x] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [x] There are no unused variables and/or imports in the modified classes.
- [x] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

==============================================================================

Creación de un miembro para prueba por Postman

![Snag_232e14a](https://user-images.githubusercontent.com/92120975/172949445-5e46cc16-5ddb-430a-b461-9fba2df73712.png)

Miembro creado en la base de datos

![Snag_2337107](https://user-images.githubusercontent.com/92120975/172949521-61a3fceb-e91a-44af-aa7f-421adcda3bae.png)

Actualización de un miembro por Postman

![Snag_2342b1f](https://user-images.githubusercontent.com/92120975/172949602-7a73d4f4-e3e6-461f-aa64-3b200848f20a.png)

Miembro actualizado en la base de datos

![Snag_234fc0c](https://user-images.githubusercontent.com/92120975/172949721-66157387-56e2-4bf5-a4ee-dfe8744ecede.png)

2022-06-14 22:43 UTC, manerajona requested changes

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/controller/MemberController.java
> +        return ResponseEntity.ok().body(memberResponse);
Como no se especifica en la tarea devolver una respuesta, deberiamos retornar un 204 NO CONTENT, sin body.

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/MemberServiceImpl.java
> +            } catch (Exception exception) {
Remover el try catch por favor, las no debería lanzar excepción

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/MemberServiceImpl.java
> +                Member memberToUpdate = memberJpaRepository.getById(id);
La variable `memberToUpdate` debería salir del contenido del optional: `optional.get()`

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/repository/MemberRepository.java
> +    Member getById(Long id);
Este metodo no es necesario, ya está implementado el `findById()` en la interfaz `PagingAndSortingRepository`

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/MemberService.java
> +    MemberResponse updateMember(Long id, Member entity);
Como no se especifica que devuelva un body, debería el método debería ser `void`.

2022-06-14 22:43 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/MemberServiceImpl.java
> +    private final MemberControllerMapperImpl mapper;
`MemberControllerMapper` es una clase de la capa rest, no debería estar en el service.

2022-06-15 14:19 UTC, hernancostarelli commented
Correcciones hechas

2022-06-15 22:40 UTC, merged