[OT210-46] Endpoint Creación Novedades
alkemyTech/OT210-server pull request #64
Opened 2022-06-10 13:47 UTC by mike47k

## Why is this change required?

COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG

Criterios de aceptación:
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla News. Antes de almacenarla, deberá asignarle la columna category con el valor "news".

### Motivation and Summary

### Type of change
- [ ] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [ ] Traceability between this change and Jira.
- [ ] ```mvn clean install``` was run and all tests completed successfully.
- [ ] There are no unused variables and/or imports in the modified classes.
- [ ] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-06-10 13:50 UTC, mike47k commented
![postmanCreateNews](https://user-images.githubusercontent.com/53406773/173080060-cc789a23-99ac-48c0-b73f-76aef3ed52f4.png)
![dbNewCreated](https://user-images.githubusercontent.com/53406773/173080071-3dfe8e46-a406-4838-939e-e8e9dbba5048.png)
![Captura desde 2022-06-10 10-42-01](https://user-images.githubusercontent.com/53406773/173080084-d94361c0-4753-4331-a7be-05b139c0f950.png)

2022-06-11 19:56 UTC, manerajona requested changes

2022-06-11 19:56 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewServiceImpl.java
> +    @Value("${default.role.id}")
agregar una nueva variable en `application.properties`. Ex: `default.category.id`

2022-06-11 19:56 UTC, manerajona commented on src/main/java/com/alkemy/ong/domain/usecase/impl/NewServiceImpl.java
> +    @Override
Agregar `@Transactional(readOnly = true)` por favor

2022-06-11 20:40 UTC, mike47k commented
listo

2022-06-13 22:33 UTC, merged