[OT210-88] Testimonial Documentation
alkemyTech/OT210-server pull request #67
Opened 2022-06-13 01:23 UTC by nicouema

## Why is this change required?

### Motivation and Summary
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Testimonios
PARA tener referencias de su funcionamiento

Criterios de aceptación:
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

![image](https://user-images.githubusercontent.com/101826700/173263103-8d0a9c9d-8d1b-451a-a988-539e4e76496b.png)

### Type of change
- [x] New feature
- [ ] New Tests
- [ ] Bug fix
- [ ] Refactor

### Checklist

- [x] Traceability between this change and Jira.
- [x] ```mvn clean install``` was run and all tests completed successfully.
- [x] There are no unused variables and/or imports in the modified classes.
- [x] There are no imports in the modified classes with the wildcard character. Ex: ```com.somepackage.*```.
- [ ] Slf4j was used for the application log instead ```System.out```.
- [ ] Public methods are documented with ```javadoc```.

2022-06-15 11:10 UTC, manerajona requested changes

2022-06-15 11:10 UTC, manerajona commented on src/main/java/com/alkemy/ong/ports/input/rs/api/TestimonialApi.java
> +            @ApiResponse(responseCode = "204", description = "No Content"),
Este update retorna `OK` con `content`.

2022-06-16 15:41 UTC, manerajona requested changes

2022-06-16 16:02 UTC, nicouema commented on src/main/java/com/alkemy/ong/ports/input/rs/api/TestimonialApi.java
> +            @ApiResponse(responseCode = "204", description = "No Content"),
![image](https://user-images.githubusercontent.com/101826700/174115025-8f07d9e1-ea40-4c30-878f-319e0fe0fe65.png)

2022-06-16 17:46 UTC, merged